config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users,  path_names: { sign_in: 'login', sign_out: 'logout' },
                      controllers: { registrations: 'users/registrations' }

  root 'projects#index'

  resources :projects do
    resources :project_users, only: %i[create destroy]
    resources :bugs
  end

  get ':not_active_storage',
      to: redirect('/'),
      constraints: { not_active_storage: %r{(?!rails/active_storage/blobs).*} }
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  has_many :bugs, dependent: :destroy

  belongs_to :creator, class_name: :User, inverse_of: :created_projects

  validates :title, presence: true, uniqueness: { case_sensitive: false }

  before_create :set_user

  private

  def set_user
    users << Current.user
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, except: %i[index new create]

  def index
    @projects = policy_scope(Project).page(params[:page]).per(10)

    @projects.each { |project| authorize project }
  end

  def new
    @project = authorize Project.new
  end

  def create
    @project = authorize current_user.created_projects.new(project_params)

    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def show
    @users = @project.users.page(params[:page]).per(10)

    @available_users = User.available(@project.id)
  end

  def edit
    # Do Nothing
  end

  def update
    if @project.update(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_path
    else
      render :index
    end
  end

  private

  def set_project
    @project = authorize Project.find_by(id: params[:id])
  end

  def project_params
    params.require(:project).permit(:title)
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
  def creator_policy_check(object, content)
    content if policy(object).creator?
  end

  def add_user_form(object_id, users)
    form_with url: project_project_users_path(object_id), class: 'rem-form', validate: true do |f|
      if users.count.positive?
        concat(
          (tag.div(class: 'form-group') do
            f.submit(:Add, class: 'btn')
          end)
        )
      end

      concat(
        (tag.div(class: 'scroll-able') do
          render partial: 'project_users/user_check_box', collection: users, as: :user, locals: { form: f }
        end)
      )
    end
  end
end

app/views/projects/_form.html.erb
<%= form_with model: project, local: true, validate: true do |f| %>
  <%= render partial: 'shared/error_messages', locals: {resource: project} %>

  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div>
    <%= f.submit class: 'btn' %>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div class='panel-group'>
  <div class='panel panel-default'>
    <div class='panel-heading'>
      <h4 class='panel-title row'>
        <a data-toggle='collapse' href='#collapse<%= project.id %>' class='col-xs-8' ><%= project.title %></a>
        <%= link_to 'View Details', project_path(project.id), class: 'col-xs-4 text-right text-primary' %>
      </h4>
    </div>

    <div id='collapse<%= project.id %>' class='panel-collapse collapse'>
      <ul class='list-group'>
        <li class='list-group-item'><%= link_to 'See all bugs', project_bugs_path(project.id), class: 'see-all-bugs' %></li>
      </ul>
    </div>
  </div>
</div>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render partial: 'form', locals: { project: @project } %>

app/views/projects/index.html.erb
<%= render 'shared/flash_errors' %>

<div class='d-flex-space-between'>
  <h2>Projects</h2>
  <%= show_if_manager create_link_button new_project_path %>
</div>

<%= paginate @projects %>

<div class='line'></div>

<%= render partial: 'project', collection: @projects, as: :project %>

app/views/projects/new.html.erb
<h2>Create Project</h2>
<%= render partial: 'form', locals: { project: @project } %>

app/views/projects/show.html.erb
<div class='row'>
  <div class='col-md-9 col-xs-12'>
    <div class='d-flex-space-between mb-2'>
      <%= render partial: 'bugs/bug_nav_links', locals: { id: @project.id } %>

      <div>
        <h2><%= @project.title %></h2>
        <p>(<%= link_to 'See Bugs', project_bugs_path(@project.id) %>)</p>
        <p><strong>Created by: </strong><%= @project.creator.name %></p>
        <span><%= creator_policy_check @project, (link_to 'Edit', edit_project_path(@project.id), class: 'mr-1') %></span>
        <span><%= creator_policy_check @project, (link_to 'Delete', project_path(@project.id), method: :delete, data: { confirm: 'Are you sure?' }) %></span>
      </div>
    </div>

    <%= render partial: 'project_users/index', locals: { users: @users, project: @project } %>

    <%= paginate @users %>
  </div>

  <div class='col-md-3 col-xs-12'>
    <%= creator_policy_check @project, add_user_form(@project.id, @available_users) %>
  </div>
</div>