config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users,  path_names: { sign_in: 'login', sign_out: 'logout' },
                      controllers: { registrations: 'users/registrations' }

  root 'projects#index'

  resources :projects do
    resources :project_users, only: %i[create destroy]
    resources :bugs
  end

  get ':not_active_storage',
      to: redirect('/'),
      constraints: { not_active_storage: %r{(?!rails/active_storage/blobs).*} }
end

app/models/project_user.rb
# frozen_string_literal: true

class ProjectUser < ApplicationRecord
  belongs_to :user
  belongs_to :project

  validates :project_id, uniqueness: { scope: :user_id }
end

app/controllers/project_users_controller.rb
# frozen_string_literal: true

class ProjectUsersController < ApplicationController
  rescue_from NoMethodError, with: :redirection_path

  def create
    params[:ids].each do |id|
      break unless authorize ProjectUser.create(user_id: id, project_id: params[:project_id])
    end

    redirect_to project_path(params[:project_id])
  end

  def destroy
    @project_user = authorize ProjectUser.find_by(user_id: params[:id], project_id: params[:project_id])

    if @project_user.destroy
      redirect_to project_path(params[:project_id])
    else
      render 'projects/show'
    end
  end

  private

  def redirection_path
    redirect_to project_path(params[:project_id]), alert: 'Page does not exist!'
  end
end

app/helpers/project_users_helper.rb
# frozen_string_literal: true

module ProjectUsersHelper
  def show_if_creator_not_manager_row(object, user, content)
    content if policy(object).remove_user_view?(user)
  end
end

app/views/project_users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'project_users/user', locals: { project: project }, collection: users, as: :user %>
  </tbody>
</table>

app/views/project_users/_user.html.erb
<tr>
  <td><%= user.name %></td>
  <td><%= user.email %></td>
  <td><%= user.user_type.humanize %></td>
  <td><%= show_if_creator_not_manager_row project, user, (link_to 'Delete', project_project_user_path(params[:id], user.id), method: :delete, data: { confirm: 'Are you sure?' }) %></td>
</tr>

app/views/project_users/_user_check_box.html.erb
<div class='d-flex-space-between-vertical-center form-group user-check-box'>
  <div>
    <p class='cb-user-name'><%= user.name %></p>
    <p class='cb-user-prop'>Role: <%= user.user_type %></p>
    <p class='cb-user-prop'>(<%= user.email %>)</p>
  </div>

  <%= form.check_box :ids, {multiple: true}, user.id, nil %>
</div>

<div class='line' />